In [25]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [26]:
dataset=pd.read_csv('Data.csv')
X=dataset.iloc[:,:-1].values  
y=dataset.iloc[:,-1].values
##iloc means locate index(rows,colums)
print("Features Data: \n ",X)
print("Target Data: \n ",y)

Features Data: 
  [['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
Target Data: 
  ['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


##### Encoding: Here we will apply the encoding scheme on the country colum(Categorical Data) because we have repition of countries names and we will calculate the result multiple times for the same country. So that's why we will represent them with One Hot encoding scheme.

# Encoding the independant variable

In [27]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoding',OneHotEncoder(),[0])],remainder='passthrough')
X=np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 nan]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 nan 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


# Encoding the dependant variable

In [28]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


# Splitting the data into train and test

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [30]:
print("X_train:\n ",X_train)

X_train:
  [[0.0 1.0 0.0 40.0 nan]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 0.0 1.0 nan 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [31]:
print("y_train:\n ",y_train)

y_train:
  [1 1 1 0 1 0 0 1]


In [32]:
print("X_test:\n ",X_test)

X_test:
  [[0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 50.0 83000.0]]


In [33]:
print("y_test:\n ",y_test)

y_test:
  [0 0]


**Feature Scaling is being done so to eliminate the dominance of 1 particular fetaure so that all features will gets the equal chance. It depends on your dataset and it don't necessarily needed all the time.
There are 2 ways to do feature scaling:

**1-Standarisation: 
s=[Xi-mean(x)]/[standard deviation(x)] {All features value will be between -3,+3}

Explain: Here we will subtract the each value of the feature by the mean of that feature and then divide it with the standard deviation of that feature.

**2-Normalisation:
n=[Xi-min(x)]/[max(x)-min(x)] {All features value will be between 0,1}

Explain: Here we will subtract the each value of the feature by the minimum value of that feature and then divide it with the max(feature)-min(feature) of that feature.

**Standarisation will work all the time and Normalisation works good on the normalized distributions so standarisation is prefferd over normalisation.

# Feature Scaling

In [34]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train[:,3:]=sc.fit_transform(X_train[:,3:])
X_test[:,3:]=sc.transform(X_test[:,3:])

In [35]:
print(X_train)

[[0.0 1.0 0.0 0.2531580199220386 nan]
 [1.0 0.0 0.0 -0.23014365447458116 0.44897082661305115]
 [0.0 0.0 1.0 -1.841149235796647 -1.4170641714974423]
 [0.0 0.0 1.0 nan -1.0242146982110225]
 [1.0 0.0 0.0 1.5419624849796914 1.62751924647231]
 [0.0 0.0 1.0 -0.06904309634237459 -0.14030338331657835]
 [1.0 0.0 0.0 0.8975602524508649 0.9400326682210757]
 [1.0 0.0 0.0 -0.5523447707389944 -0.4349404882813931]]


In [36]:
print(X_test)

[[0.0 1.0 0.0 -1.3578475614000274 -0.8277899615678128]
 [0.0 1.0 0.0 1.8641636012441045 2.02036871975873]]
